/* **** Generated by ****
EXEC dbo.pub_MergeScript_Generate @SourceTable = '[dbo].[Table1]', @IsForSSDT = 1
*/
PRINT 'Update rows in [dbo].[Table1]'
GO

MERGE [dbo].[Table1] AS t /* Target */
USING
(
 VALUES 
 (1, 'Name 1', 'Description 1 ', '2020-01-12'),
 (2, 'Name 2', ' Description 2', '2020-01-13')
)
AS s /* Source */ ([Id], [Name], [Description], [TimeStamp])
ON t.Id = s.Id

-- insert new rows
WHEN NOT MATCHED BY TARGET THEN
 INSERT
  ([Id], [Name], [Description], [TimeStamp])
 VALUES
  (s.[Id], s.[Name], s.[Description], s.[TimeStamp])

-- update matched rows
WHEN MATCHED THEN
 UPDATE SET
  t.[Name] = s.[Name],
  t.[Description] = s.[Description],
  t.[TimeStamp] = s.[TimeStamp]

-- delete rows that are in the target but not the source
WHEN NOT MATCHED BY SOURCE THEN
 DELETE
;
GO

PRINT ''
PRINT 'Operation applied [dbo].[Table1]'
PRINT ''
GO